name: CI - Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Emscripten
        run: |
          sudo apt-get update
          sudo apt-get install -y emscripten

      - name: Initialize and update git submodules
        run: git submodule update --init --recursive

      - name: Build WebAssembly module
        run: chmod +x build.sh && ./build.sh

      - name: Verify WASM files exist
        run: |
          if [ ! -f ./wasm/equations_parser.js ]; then
            echo "❌ equations_parser.js is missing!"
            exit 1
          fi
          echo "✅ WASM module built successfully"
          ls -la wasm/

      - name: Run tests
        run: npm test -- --run

      # Optional: upload coverage if your `npm test` generates it
      # - name: Upload coverage report
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-${{ matrix.os }}-node${{ matrix.node }}
      #     path: coverage
